const topicsPathwayArray = [
	{
		skillId: 10,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "multiplicationTable",
		skillDisplayName: "Multiplication Table",
		description: "Memorize multiplication facts up to 12x12.",
		duration: 10,
		level: 10,
		isLive: true,
	},
	{
		skillId: 20,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "multiplicationMix",
		skillDisplayName: "Multiplication Tables Mixed",
		description: "Multiplication tables mixed.",
		duration: 10,
		level: 20,
		isLive: true,
	},
	{
		skillId: 30,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "squaringNumbers",
		skillDisplayName: "Squaring Numbers",
		description: "Square numbers up to 12 squared.",
		duration: 10,
		level: 30,
		isLive: true,
	},
	{
		skillId: 40,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "cubingNumbers",
		skillDisplayName: "Cubing Numbers",
		description: "Cube numbers up to 7 cubed.",
		duration: 10,
		level: 40,
		isLive: true,
	},
	{
		skillId: 50,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "multiplyingFractions",
		skillDisplayName: "Multiplying Fractions",
		description: "Multiply fractions and mixed numbers.",
		duration: 10,
		level: 50,
		isLive: false,
	},
	{
		skillId: 60,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "multiplication",
		topicDisplayName: "Multiplication",
		skill: "orderOfOperations",
		skillDisplayName: "Order of Operations",
		description: "Apply the order of operations in multi-step problems.",
		duration: 10,
		level: 60,
		isLive: false,
	},
	{
		skillId: 100,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "functionNotation",
		skillDisplayName: "Function Notation",
		description: "Evaluate functions.",
		duration: 10,
		level: 100,
		isLive: true,
		path: "/functionNotation",
	},
	{
		skillId: 110,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "plottingPointsPolynomials",
		skillDisplayName: "Polynomial Function",
		description: "Plot and analyze polynomial functions.",
		duration: 10,
		level: 110,
		isLive: true,
		path: "/plottingPointsPolynomials",
	},
	{
		skillId: 120,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "plottingPointsSine",
		skillDisplayName: "Sine Function",
		description: "Plot points and understand sine function behavior.",
		duration: 10,
		level: 120,
		isLive: true,
		path: "/plottingPoints/Sine",
	},
	{
		skillId: 130,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "plottingPointsCosine",
		skillDisplayName: "Cosine Function",
		description: "Plot points and understand cosine function behavior.",
		duration: 10,
		level: 130,
		isLive: true,
		path: "/plottingPoints/Cosine",
	},
	{
		skillId: 140,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "identifyingFunctions",
		skillDisplayName: "Identifying Functions",
		description: "Identify and classify different types of functions.",
		duration: 10,
		level: 140,
		isLive: true,
		path: "/identifyingFunctions",
	},
	{
		skillId: 150,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "functions",
		topicDisplayName: "Functions",
		skill: "equationsOfLines",
		skillDisplayName: "Equations of Lines",
		description: "Find and work with linear equations and their properties.",
		duration: 10,
		level: 150,
		isLive: true,
		path: "/equationsOfLines",
	},
	{
		skillId: 200,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "exponents",
		topicDisplayName: "Exponents",
		skill: "positive",
		skillDisplayName: "Simple Exponents",
		description: "Work with positive integer exponents and basic exponential rules.",
		duration: 10,
		level: 200,
		isLive: true,
		path: "/exponentsVariety/positive",
	},
	{
		skillId: 210,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "exponents",
		topicDisplayName: "Exponents",
		skill: "negative",
		skillDisplayName: "Negative Exponents",
		description: "Understand and apply negative exponent rules.",
		duration: 10,
		level: 210,
		isLive: true,
		path: "/exponentsVariety/negative",
	},
	{
		skillId: 220,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "exponents",
		topicDisplayName: "Exponents",
		skill: "fractional",
		skillDisplayName: "Fractional Exponents",
		description: "Work with fractional exponents and radical expressions.",
		duration: 10,
		level: 220,
		isLive: true,
		path: "/exponentsVariety/fractional",
	},
	{
		skillId: 230,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "exponents",
		topicDisplayName: "Exponents",
		skill: "negativeFractional",
		skillDisplayName: "Negative Fractional Exponents",
		description: "Apply rules for negative fractional exponents.",
		duration: 10,
		level: 230,
		isLive: true,
		path: "/exponentsVariety/negativeFractional",
	},
	{
		skillId: 240,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "exponents",
		topicDisplayName: "Exponents",
		skill: "mixed",
		skillDisplayName: "Mix of All Types",
		description: "Practice all types of exponent rules in mixed problems.",
		duration: 10,
		level: 240,
		isLive: true,
		path: "/exponentsVariety/mixed",
	},
	{
		skillId: 300,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "quadratics",
		topicDisplayName: "Quadratics",
		skill: "differenceOfSquares",
		skillDisplayName: "Difference of Squares",
		description: "Factor expressions using the difference of squares formula.",
		duration: 10,
		level: 300,
		isLive: true,
		path: "/factoringQuadratics/differenceOfSquares",
	},
	{
		skillId: 310,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "quadratics",
		topicDisplayName: "Quadratics",
		skill: "factoringQuadratics",
		skillDisplayName: "Factoring Quadratics",
		description: "Factor quadratic expressions and solve quadratic equations.",
		duration: 10,
		level: 310,
		isLive: true,
		path: "/factoringQuadratics/factoringQuadratics",
	},
	{
		skillId: 401,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleWarmUpFirstQuadrant",
		skillDisplayName: "Warm Up: First Quadrant",
		description: "Warm up exercises for unit circle coordinates in the first quadrant.",
		duration: 10,
		level: 401,
		isLive: true,
		path: "/unitCircle/100",
	},
	{
		skillId: 402,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleWarmUpSecondQuadrant",
		skillDisplayName: "Warm Up: Second Quadrant",
		description: "Warm up exercises for unit circle coordinates in the second quadrant.",
		duration: 10,
		level: 402,
		isLive: true,
		path: "/unitCircle/120",
	},
	{
		skillId: 403,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleWarmUpThirdQuadrant",
		skillDisplayName: "Warm Up: Third Quadrant",
		description: "Warm up exercises for unit circle coordinates in the third quadrant.",
		duration: 10,
		level: 403,
		isLive: true,
		path: "/unitCircle/140",
	},
	{
		skillId: 404,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleWarmUpFourthQuadrant",
		skillDisplayName: "Warm Up: Fourth Quadrant",
		description: "Warm up exercises for unit circle coordinates in the fourth quadrant.",
		duration: 10,
		level: 404,
		isLive: true,
		path: "/unitCircle/160",
	},
	{
		skillId: 431,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleSineFirstQuadrant",
		skillDisplayName: "Practice: Sine - First Quadrant",
		description: "Practice sine values on the unit circle in the first quadrant.",
		duration: 10,
		level: 431,
		isLive: true,
		path: "/unitCircle/200",
	},
	{
		skillId: 432,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleSineFirstHalf",
		skillDisplayName: "Practice: Sine - First Half",
		description: "Practice sine values on the unit circle in the first half.",
		duration: 10,
		level: 432,
		isLive: true,
		path: "/unitCircle/220",
	},
	{
		skillId: 433,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleSineFullCircle",
		skillDisplayName: "Practice: Sine - Full Circle",
		description: "Practice sine values on the unit circle for the full circle.",
		duration: 10,
		level: 433,
		isLive: true,
		path: "/unitCircle/240",
	},
	{
		skillId: 434,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleCosineFirstQuadrant",
		skillDisplayName: "Practice: Cosine - First Quadrant",
		description: "Practice cosine values on the unit circle in the first quadrant.",
		duration: 10,
		level: 434,
		isLive: true,
		path: "/unitCircle/300",
	},
	{
		skillId: 435,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleCosineFirstHalf",
		skillDisplayName: "Practice: Cosine - First Half",
		description: "Practice cosine values on the unit circle in the first half.",
		duration: 10,
		level: 435,
		isLive: true,
		path: "/unitCircle/320",
	},
	{
		skillId: 436,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleCosineFullCircle",
		skillDisplayName: "Practice: Cosine - Full Circle",
		description: "Practice cosine values on the unit circle for the full circle.",
		duration: 10,
		level: 436,
		isLive: true,
		path: "/unitCircle/340",
	},
	{
		skillId: 437,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleTangentFirstQuadrant",
		skillDisplayName: "Practice: Tangent - First Quadrant",
		description: "Practice tangent values on the unit circle in the first quadrant.",
		duration: 10,
		level: 437,
		isLive: true,
		path: "/unitCircle/400",
	},
	{
		skillId: 438,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleTangentFirstHalf",
		skillDisplayName: "Practice: Tangent - First Half",
		description: "Practice tangent values on the unit circle in the first half.",
		duration: 10,
		level: 438,
		isLive: true,
		path: "/unitCircle/420",
	},
	{
		skillId: 439,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleTangentFullCircle",
		skillDisplayName: "Practice: Tangent - Full Circle",
		description: "Practice tangent values on the unit circle for the full circle.",
		duration: 10,
		level: 439,
		isLive: true,
		path: "/unitCircle/440",
	},
	{
		skillId: 471,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleFirstQuadrant",
		skillDisplayName: "Test: First Quadrant",
		description: "Test your knowledge of unit circle values in the first quadrant.",
		duration: 10,
		level: 471,
		isLive: true,
		path: "/unitCircle/1001",
	},
	{
		skillId: 472,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleFirstHalf",
		skillDisplayName: "Test: First Half",
		description: "Test your knowledge of unit circle values in the first half.",
		duration: 10,
		level: 472,
		isLive: true,
		path: "/unitCircle/1020",
	},
	{
		skillId: 473,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "unitCircleFullCircle",
		skillDisplayName: "Test: Full Circle",
		description: "Test your knowledge of unit circle values for the full circle.",
		duration: 10,
		level: 473,
		isLive: true,
		path: "/unitCircle/1040",
	},
	{
		skillId: 490,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "summerPrep",
		unitDisplayName: "Summer Prep",
		topic: "unitCircle",
		topicDisplayName: "Unit Circle",
		skill: "essentialUnitCircle",
		skillDisplayName: "The Absolute Essentials",
		description: "Master the absolute essential unit circle values and concepts.",
		duration: 10,
		level: 490,
		isLive: true,
		path: "/unitCircle/1000",
	},
	{
		skillId: 1100,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "limits",
		unitDisplayName: "Limits",
		topic: "evaluatingLimits",
		topicDisplayName: "Evaluating Limits",
		skill: "leftHandedLimits",
		skillDisplayName: "Evaluating Left-Handed Limits",
		description: "Master the techniques for evaluating left-handed limits.",
		duration: 10,
		level: 1100,
		isLive: true,
		path: "/evaluatingLimits/1100",
	},
	{
		skillId: 2010,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "powerRule",
		topicDisplayName: "Power Rule",
		skill: "integerExponents",
		skillDisplayName: "Power Rule with Integer Exponents",
		description: "Apply the power rule to differentiate functions with integer exponents.",
		duration: 10,
		level: 2010,
		isLive: true,
		path: "/powerRuleSkills/integerExponents",
	},
	{
		skillId: 2020,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "powerRule",
		topicDisplayName: "Power Rule",
		skill: "negativeExponents",
		skillDisplayName: "Power Rule with Negative Exponents",
		description: "Apply the power rule to differentiate functions with negative exponents.",
		duration: 10,
		level: 2020,
		isLive: true,
		path: "/powerRuleSkills/negativeExponents",
	},
	{
		skillId: 2030,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "powerRule",
		topicDisplayName: "Power Rule",
		skill: "fractionalExponents",
		skillDisplayName: "Power Rule with Fractional Exponents",
		description: "Apply the power rule to differentiate functions with fractional exponents.",
		duration: 10,
		level: 2030,
		isLive: true,
		path: "/powerRuleSkills/fractionalExponents",
	},
	{
		skillId: 2040,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "powerRule",
		topicDisplayName: "Power Rule",
		skill: "negativeFractionalExponents",
		skillDisplayName: "Power Rule with Negative Fractional Exponents",
		description: "Apply the power rule to differentiate functions with negative fractional exponents.",
		duration: 10,
		level: 2040,
		isLive: true,
		path: "/powerRuleSkills/negativeFractionalExponents",
	},
	{
		skillId: 2050,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "powerRule",
		topicDisplayName: "Power Rule",
		skill: "powerRuleMix",
		skillDisplayName: "Power Rule Mix",
		description: "Practice the power rule with mixed types of exponents.",
		duration: 10,
		level: 2050,
		isLive: true,
		path: "/derivatives/330",
	},
	{
		skillId: 2110,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "trigonometricDerivatives",
		topicDisplayName: "Trigonometric Derivatives",
		skill: "simpleTrigonometric",
		skillDisplayName: "Trig Derivatives",
		description: "Learn to differentiate basic trigonometric functions.",
		duration: 10,
		level: 2110,
		isLive: true,
		path: "/trigonometricDerivatives/1100",
	},
	{
		skillId: 2120,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "trigonometricDerivatives",
		topicDisplayName: "Trigonometric Derivatives",
		skill: "simpleChainRuleTrigonometric",
		skillDisplayName: "Chain Rule Trig Derivatives",
		description: "Apply the chain rule to differentiate composite trigonometric functions.",
		duration: 10,
		level: 2120,
		isLive: true,
		path: "/trigonometricDerivatives/1110",
	},
	{
		skillId: 2210,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "naturalDerivatives",
		topicDisplayName: "Natural Derivatives",
		skill: "naturalExponential",
		skillDisplayName: "Natural Exponential",
		description: "Learn to differentiate natural exponential functions.",
		duration: 10,
		level: 2210,
		isLive: true,
		path: "/naturalDerivatives/500",
	},
	{
		skillId: 2220,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "naturalDerivatives",
		topicDisplayName: "Natural Derivatives",
		skill: "simpleNaturalLog",
		skillDisplayName: "Natural Log",
		description: "Learn to differentiate natural logarithmic functions.",
		duration: 10,
		level: 2220,
		isLive: true,
		path: "/naturalDerivatives/520",
	},
	{
		skillId: 2230,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "naturalDerivatives",
		topicDisplayName: "Natural Derivatives",
		skill: "comlexNaturalLog",
		skillDisplayName: "Natural Log (Complex)",
		description: "Learn to differentiate complex natural logarithmic functions.",
		duration: 10,
		level: 2230,
		isLive: true,
		path: "/naturalDerivatives/530",
	},
	{
		skillId: 2240,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "naturalDerivatives",
		topicDisplayName: "Natural Derivatives",
		skill: "exponentialFunctionsBaseA",
		skillDisplayName: "General Exponential Functions",
		description: "Learn to differentiate general exponential functions with arbitrary bases.",
		duration: 10,
		level: 2240,
		isLive: true,
		path: "/naturalDerivatives/550",
	},
	{
		skillId: 2250,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "derivatives",
		unitDisplayName: "Derivatives",
		topic: "naturalDerivatives",
		topicDisplayName: "Natural Derivatives",
		skill: "logFunctionsBaseA",
		skillDisplayName: "General Log Functions",
		description: "Learn to differentiate general logarithmic functions with arbitrary bases.",
		duration: 10,
		level: 2250,
		isLive: true,
		path: "/naturalDerivatives/560",
	},
	{
		skillId: 3100,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "basicIntegration",
		topicDisplayName: "Basic Integration",
		skill: "indefiniteIntegralsSingleTerm",
		skillDisplayName: "Single Term Integration",
		description: "Learn to integrate single term functions using basic integration rules.",
		duration: 10,
		level: 3100,
		isLive: true,
		path: "/integration/3010",
	},
	{
		skillId: 3100,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "basicIntegration",
		topicDisplayName: "Basic Integration",
		skill: "indefiniteIntegralsBinomial",
		skillDisplayName: "Binomial Integration",
		description: "Learn to integrate binomial expressions using integration techniques.",
		duration: 10,
		level: 3100,
		isLive: true,
		path: "/integration/3020",
	},
	{
		skillId: 3100,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "basicIntegration",
		topicDisplayName: "Basic Integration",
		skill: "indefiniteIntegralsPolynomial",
		skillDisplayName: "Polynomial Integration",
		description: "Learn to integrate polynomial functions using power rule for integration.",
		duration: 10,
		level: 3100,
		isLive: true,
		path: "/integration/3030",
	},
	{
		skillId: 3200,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "trigonometricIntegration",
		topicDisplayName: "Trigonometric Integration",
		skill: "indefiniteIntegralsTrigonometric",
		skillDisplayName: "Trigonometric Integration",
		description: "Learn to integrate trigonometric functions using trigonometric integration rules.",
		duration: 10,
		level: 3200,
		isLive: true,
		path: "/integration/3040",
	},
	{
		skillId: 3300,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "naturalIntegration",
		topicDisplayName: "Natural Integration",
		skill: "indefiniteIntegralsNaturalExponential",
		skillDisplayName: "Natural Exponential Integration",
		description: "Learn to integrate natural exponential functions using exponential integration rules.",
		duration: 10,
		level: 3300,
		isLive: true,
		path: "/integration/3050",
	},
	{
		skillId: 3300,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "naturalIntegration",
		topicDisplayName: "Natural Integration",
		skill: "indefiniteIntegralsNaturalLog",
		skillDisplayName: "Natural Log Integration",
		description: "Learn to integrate natural logarithmic functions using integration by parts.",
		duration: 10,
		level: 3300,
		isLive: true,
		path: "/integration/3060",
	},
	{
		skillId: 3300,
		course: "AP Calculus AB",
		section: "calculusSkills",
		unit: "integrals",
		unitDisplayName: "Integrals",
		topic: "naturalIntegration",
		topicDisplayName: "Natural Integration",
		skill: "indefiniteIntegralsNaturalLogBinomial",
		skillDisplayName: "Binomial Natural Log Integration",
		description: "Learn to integrate binomial natural logarithmic functions using advanced integration techniques.",
		duration: 10,
		level: 3300,
		isLive: true,
		path: "/integration/3070",
	},

];

export default topicsPathwayArray;
